server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name sub.79-137-197-51.sslip.io cover.79-137-197-51.sslip.io;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
